### ISSUE TITLE
Warning window.devToolsExtension is deprecated in favor of window.__REDUX_DEVTOOLS_EXTENSION__

### ISSUE THREAD

**Issue by iexplore** [zalmoxisus/remotedev#14]
Question from a Redux middleware Newby so forgive me if this is a stupid question.

I am using remotedev with Mobx-State-Tree and getting this warning:
`window.devToolsExtension` is deprecated in favor of `window.__REDUX_DEVTOOLS_EXTENSION__`, and will be removed in next version of Redux 

Can I solve this somehow?

**Comment by zalmoxisus** [comment]
Thanks for reporting it. I renamed it in `0.2.9`.
