### ISSUE TITLE
ExtractState misses second argument.

### ISSUE THREAD

**Issue by mweststrate** [zalmoxisus/remotedev#3]
The readme shows extractState with a callback function, however, the implementation for that seems to be missing: https://github.com/zalmoxisus/remotedev/blob/master/src/devTools.js#L9

**Comment by zalmoxisus** [comment]
@mweststrate, thanks a lot for investigating this! Don't remember from which implementation I took this snippet, but it doesn't make sense to have it asynchronous.

**Comment by mweststrate** [comment]
i actually liked it, it saves some if... then... 😊. not really important
but i often use these kinda of maybe nomads internally

Op zo 16 okt. 2016 11:05 schreef Mihail Diordiev <notifications@github.com>:
