### ISSUE TITLE
Should changes.state be parsed?

### ISSUE THREAD

**Issue by rob3c** [zalmoxisus/remotedev#5]
Hi, as I mentioned in the previous issue https://github.com/zalmoxisus/remotedev/issues/4 I just created, I created a custom proxy for using `remotedev` with `@ngrx/store` via `@ngrx/store-devtools`.

I'm not a React/Redux expert and am unsure of what the expected format is, but I noticed that `changes.state` is a JSON string instead of an object in the subscribe callback. Currently, in my attempt to get time-travel debugging working, I'm calling `changes.state = JSON.parse(changes.state)` in my wrapper before passing it to the ngrx store devtools. Is this a bug in remotedev, or should the store devtools be parsing it on their end?

Thanks in advance!

**Comment by zalmoxisus** [comment]
Yes, parsing the state is an expensive operation, so you should call it on your side. However, there's a helper `extractState(changes)` you can call. It uses `jsan.parse` under the hood, which unlike `JSON.parse` handle also circular references.

**Comment by rob3c** [comment]
Thanks - good to know!
